name: Release Fedora Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and test using Docker
      run: |
        docker buildx build --target test --load -t stone-prover-test .  # Build and run the test stage
        docker create --name temp stone-prover-test
        docker cp temp:/usr/local/bin/cpu_air_prover ./cpu_air_prover
        docker cp temp:/usr/local/bin/cpu_air_verifier ./cpu_air_verifier
        docker rm temp

    - name: Package RPM
      run: |
        docker run --rm -v $(pwd):/rpmbuild/SOURCES fedora:latest \
          bash -c "dnf install -y rpm-build && \
                   mkdir -p /rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} && \
                   cp /rpmbuild/SOURCES/stone-prover.spec /rpmbuild/SPECS/ && \
                   rpmbuild -ba /rpmbuild/SPECS/stone-prover.spec \
                   --define \"version ${GITHUB_REF#refs/tags/v}\" \
                   --define \"_topdir /rpmbuild\""
        
    - name: Upload RPM to GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: ./RPMS/x86_64/*.rpm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
