name: Release Fedora Package

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger the workflow when a new tag is pushed (e.g., v1.0.0)

jobs:
  build:
    runs-on: fedora-latest  # Use Fedora environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo dnf update -y
        sudo dnf install -y rpm-build gcc make bazelisk python3-pip  # Install required packages

    - name: Build and package RPM
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}  # Set up RPM build directories
        cp ./stone-prover.spec ~/rpmbuild/SPECS/  # Copy the .spec file to the RPM build area
        rpmbuild -ba ~/rpmbuild/SPECS/stone-prover.spec \
          --define "_topdir $HOME/rpmbuild" \
          --define "version ${GITHUB_REF#refs/tags/}" \
          --define "arch x86_64"

    - name: Verify RPM
      run: ls -la ~/rpmbuild/RPMS/x86_64/  # Verify that the RPM was created

    - name: Upload RPM to GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: ~/rpmbuild/RPMS/x86_64/*.rpm  # Upload the RPM package to the release
        