name: Release Fedora Package

on:
  push:
    tags:
      - 'v*.*.*'  # Runs when a tag is pushed (e.g., v1.0.0)

jobs:
  build:
    runs-on: fedora-latest  # Use Fedora environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo dnf update -y
        sudo dnf install -y rpm-build gcc make bazel  # Install RPM tools, compilers, and Bazel

    - name: Build with Bazel
      run: |
        bazel build //src:stone-prover  # Replace with the correct Bazel build target for stone-prover

    - name: Package RPM
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp ./stone-prover.spec ~/rpmbuild/SPECS/
        rpmbuild -ba ~/rpmbuild/SPECS/stone-prover.spec \
          --define "_topdir $HOME/rpmbuild" \
          --define "version ${GITHUB_REF#refs/tags/}" \
          --define "arch x86_64"

    - name: Verify RPM
      run: ls -la ~/rpmbuild/RPMS/x86_64/

    - name: Upload RPM to GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: ~/rpmbuild/RPMS/x86_64/*.rpm
