name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, fedora-latest]  # Add Fedora here

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and package (with different Dockerfiles per OS)
      run: |
        if [ "${{ matrix.os }}" == "fedora-latest" ]; then
          docker buildx build --target target --file Dockerfile.fedora --load -t stone-prover-fedora .
        else
          docker buildx build --target target --file Dockerfile --load -t stone-prover-${{ matrix.os }} .
        fi
        docker create --name temp stone-prover-${{ matrix.os }}
        docker cp temp:/usr/local/bin/cpu_air_prover ./cpu_air_prover
        docker cp temp:/usr/local/bin/cpu_air_verifier ./cpu_air_verifier
        docker rm temp

    - name: Package RPM (for Fedora)
      if: matrix.os == 'fedora-latest'
      run: |
        docker run --rm -v $(pwd):/rpmbuild/SOURCES fedora:latest \
          bash -c "dnf install -y rpm-build && \
                   mkdir -p /rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} && \
                   cp /rpmbuild/SOURCES/stone-prover.spec /rpmbuild/SPECS/ && \
                   rpmbuild -ba /rpmbuild/SPECS/stone-prover.spec \
                   --define \"version ${GITHUB_REF#refs/tags/v}\" \
                   --define \"_topdir /rpmbuild\""

    - name: Upload files to a GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./cpu_air_prover
          ./cpu_air_verifier
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
